jhipster:
    registry:
        password: admin
    security:
        authentication:
            jwt:
                secret: training-secret123
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/eureka
configserver:
  status: Connected to GIT repository with jhipster config server for Minikube!
logging:
    file: ${spring.application.name}+'.log'